name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to Heroku
        uses: akhileshns/heroku-deploy@bf72a2f486f950d3c6b1be566f8717f998bbce51
        if: | # executed only when the change is merged or pushed to master AND commit messages do not contain keyword '#skip'.
          github.event_name == 'push' && 
          !contains(toJSON(github.event.commits.*.message), '#skip')
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "full-stackopen-cicd"
          heroku_email: "mika.honkanen@gmail.com"
          healthcheck: "https://full-stackopen-cicd.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  tag_deployed_release:
    needs: simple_deployment_pipeline # the pipeline jobs must be successfully completed before creating a new release tag. 
    runs-on: ubuntu-18.04
    if: | # executed only when the change is merged or pushed to master AND commit messages do not contain keyword '#skip'.
      github.event_name == 'push' && 
      !contains(toJSON(github.event.commits.*.message), '#skip')
    steps:
    - uses: actions/checkout@v2
    - name: bump version and push tag
      uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch        
