name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.8.8
        if: ${{ github.event_name == 'push' }} # executed only when the change is merged or pushed to master.
        if: "!contains(toJSON(github.event.commits.*.message), '#skip')" # deployment is skipped if keyword '#skip' is found from commit messages.
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "full-stackopen-cicd"
          heroku_email: "mika.honkanen@gmail.com"
          healthcheck: "https://full-stackopen-cicd.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
  tag_deployed_release:
    needs: simple_deployment_pipeline # the pipeline jobs must be successfully completed before creating a new release tag. 
    runs-on: ubuntu-18.04
    if: ${{ github.event_name == 'push' }} # executed only when the change is merged or pushed to master.
    if: "!contains(toJSON(github.event.commits.*.message), '#skip')" # Tagging is skipped if keyword '#skip' is found from commit messages.
    steps:
    - uses: actions/checkout@v2
    - name: bump version and push tag
      uses: anothrNick/github-tag-action@1.33.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: patch        